matrix:
  include:

    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.x

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-3.x

    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4.0

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.0

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.1

    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.1

    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.2
